ALTER TABLE "EvidenceFact" ADD COLUMN IF NOT EXISTS "provenance" TEXT NOT NULL DEFAULT 'DOCUMENT_EXTRACTED';
ALTER TABLE "EvidenceFact" ADD COLUMN IF NOT EXISTS "verificationState" TEXT NOT NULL DEFAULT 'EXTRACTED';
ALTER TABLE "EvidenceFact" ADD COLUMN IF NOT EXISTS "sourceId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "EvidenceFact" ADD COLUMN IF NOT EXISTS "sourceAnchorJson" TEXT NOT NULL DEFAULT '{}';
ALTER TABLE "EvidenceFact" ADD COLUMN IF NOT EXISTS "effectiveTime" TIMESTAMP(3);
