"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import {
  AlertTriangle,
  CheckCircle2,
  XCircle,
  Clock,
  FileText,
  ChevronRight,
  Download,
  RefreshCw,
  Calendar,
} from "lucide-react";
import { CaseAnalysis, CaseFinding, TimelineEvent } from "@/types/case";
import CaseHealthBadge from "@/components/CaseHealthBadge";
import Disclaimer from "@/components/Disclaimer";

function FindingRow({ finding }: { finding: CaseFinding }) {
  const icon = {
    ok: <CheckCircle2 className="h-4 w-4 text-green-500 shrink-0" />,
    warning: <AlertTriangle className="h-4 w-4 text-yellow-500 shrink-0" />,
    missing: <XCircle className="h-4 w-4 text-slate-400 shrink-0" />,
    critical: <XCircle className="h-4 w-4 text-red-500 shrink-0" />,
  }[finding.status];

  return (
    <div className="flex items-start gap-3 py-2.5 border-b border-slate-100 last:border-0">
      {icon}
      <div className="flex-1 min-w-0">
        <p className="text-sm text-slate-800 font-medium">{finding.label}</p>
        {finding.detail && <p className="text-xs text-slate-500 mt-0.5">{finding.detail}</p>}
      </div>
    </div>
  );
}

function TimelineRow({ event }: { event: TimelineEvent }) {
  return (
    <div className="flex gap-4">
      <div className="flex flex-col items-center">
        <div className={`h-3 w-3 rounded-full mt-1 shrink-0 ${
          event.source === "document" ? "bg-blue-500" :
          event.source === "both" ? "bg-green-500" : "bg-slate-300"
        }`} />
        <div className="w-px flex-1 bg-slate-200 mt-1" />
      </div>
      <div className="pb-4 min-w-0">
        <p className="text-xs font-semibold text-blue-600">{event.year}{event.date ? ` · ${event.date}` : ""}</p>
        <p className="text-sm text-slate-800 mt-0.5">{event.event}</p>
        {event.formType && (
          <span className="mt-1 inline-block text-xs bg-slate-100 text-slate-500 rounded px-1.5 py-0.5">
            {event.formType}
          </span>
        )}
      </div>
    </div>
  );
}

function exportCasePackage(analysis: CaseAnalysis) {
  const lines = [
    "IMMIGRATION CASE PACKAGE",
    "Generated by MyImmigration",
    new Date().toLocaleDateString(),
    "",
    "CURRENT SITUATION",
    analysis.currentSituation,
    "",
    "CASE HEALTH",
    analysis.caseHealth.replace("_", " ").toUpperCase(),
    "",
    "IMPORTANT FINDINGS",
    ...analysis.importantFindings.map((f) => `• ${f}`),
    "",
    "IMMIGRATION TIMELINE",
    ...analysis.timeline.map((t) => `${t.year}${t.date ? ` (${t.date})` : ""}: ${t.event}`),
    "",
    "DOCUMENTS REVIEWED",
    `${analysis.documentsReviewed} documents reviewed`,
    "",
    "POSSIBLY MISSING DOCUMENTS",
    ...analysis.documentsMissing.map((d) => `• ${d}`),
    "",
    "ISSUES DETECTED",
    `${analysis.majorIssues} issues detected`,
    "",
    "WHAT WE FOUND",
    ...analysis.findings.map((f) => `[${f.status.toUpperCase()}] ${f.label}${f.detail ? ` — ${f.detail}` : ""}`),
    "",
    "PLAIN LANGUAGE SUMMARY",
    analysis.plainLanguageSummary,
    "",
    "POSSIBLE NEXT STEPS",
    ...analysis.nextSteps.map((s) => `${s.option}: ${s.title}\n${s.description}`),
    "",
    "INCONSISTENCIES DETECTED",
    analysis.inconsistencies.length === 0
      ? "None detected"
      : analysis.inconsistencies.map(
          (i) => `[${i.severity.toUpperCase()}] ${i.field}: Narrative says "${i.narrativeSays}" — Document says "${i.documentSays}"`
        ).join("\n"),
    "",
    "DEADLINES",
    analysis.deadlines.length === 0
      ? "No specific deadlines identified"
      : analysis.deadlines.map((d) => `${d.label}: ${d.date}`).join("\n"),
    "",
    "DISCLAIMER",
    analysis.disclaimer,
  ];

  const blob = new Blob([lines.join("\n")], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "immigration-case-package.txt";
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 10000);
}

export default function DashboardPage() {
  const router = useRouter();
  const [analysis, setAnalysis] = useState<CaseAnalysis | null>(null);

  useEffect(() => {
    const stored = sessionStorage.getItem("caseAnalysis");
    if (stored) {
      setAnalysis(JSON.parse(stored));
    } else {
      router.push("/onboarding");
    }
  }, [router]);

  if (!analysis) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-slate-50">
        <p className="text-slate-500">Loading your case...</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50">
      {/* Header */}
      <header className="border-b border-slate-200 bg-white sticky top-0 z-10">
        <div className="mx-auto max-w-5xl px-4 py-4 flex items-center justify-between">
          <a href="/" className="text-xl font-bold text-blue-700">MyImmigration</a>
          <div className="flex items-center gap-3">
            <button
              onClick={() => exportCasePackage(analysis)}
              className="flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50 transition-colors"
            >
              <Download className="h-4 w-4" />
              Export Case Package
            </button>
            <a
              href="/onboarding"
              className="flex items-center gap-2 rounded-lg bg-blue-700 px-4 py-2 text-sm font-medium text-white hover:bg-blue-800 transition-colors"
            >
              <RefreshCw className="h-4 w-4" />
              New Analysis
            </a>
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-5xl px-4 py-10 space-y-8">
        {/* Case Overview Card */}
        <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <div className="flex flex-wrap items-start justify-between gap-4">
            <div>
              <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Your Case</p>
              <h1 className="mt-1 text-2xl font-bold text-slate-900">Current Situation</h1>
              <p className="mt-1 text-slate-600">{analysis.currentSituation}</p>
            </div>
            <CaseHealthBadge health={analysis.caseHealth} />
          </div>

          {/* Stats row */}
          <div className="mt-6 grid grid-cols-2 sm:grid-cols-4 gap-4">
            {[
              { label: "Documents Reviewed", value: analysis.documentsReviewed, icon: FileText, color: "text-blue-600" },
              { label: "Possibly Missing", value: analysis.documentsMissing.length, icon: AlertTriangle, color: "text-yellow-600" },
              { label: "Issues Detected", value: analysis.majorIssues, icon: XCircle, color: analysis.majorIssues > 0 ? "text-red-600" : "text-green-600" },
              { label: "Upcoming Deadlines", value: analysis.deadlines.length, icon: Calendar, color: analysis.deadlines.length > 0 ? "text-orange-600" : "text-green-600" },
            ].map(({ label, value, icon: Icon, color }) => (
              <div key={label} className="rounded-xl bg-slate-50 p-4">
                <Icon className={`h-5 w-5 ${color} mb-2`} />
                <p className="text-2xl font-bold text-slate-900">{value}</p>
                <p className="text-xs text-slate-500 mt-0.5">{label}</p>
              </div>
            ))}
          </div>

          {/* Deadlines */}
          {analysis.deadlines.length > 0 && (
            <div className="mt-4 space-y-2">
              {analysis.deadlines.map((d, i) => (
                <div key={i} className="flex items-center gap-3 rounded-lg border border-orange-200 bg-orange-50 px-4 py-3">
                  <Clock className="h-4 w-4 text-orange-600 shrink-0" />
                  <div>
                    <span className="text-sm font-medium text-orange-900">{d.label}</span>
                    <span className="ml-2 text-sm text-orange-700">{d.date}</span>
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Important findings */}
          {analysis.importantFindings.length > 0 && (
            <div className="mt-4 space-y-2">
              {analysis.importantFindings.map((finding, i) => (
                <div key={i} className="flex items-start gap-3 rounded-lg border border-blue-100 bg-blue-50 px-4 py-3">
                  <ChevronRight className="h-4 w-4 text-blue-600 mt-0.5 shrink-0" />
                  <p className="text-sm text-blue-900">{finding}</p>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Two-column grid */}
        <div className="grid lg:grid-cols-2 gap-8">
          {/* What We Found */}
          <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
            <h2 className="text-lg font-bold text-slate-900 mb-4">What We Found</h2>
            {analysis.findings.length > 0 ? (
              <div>
                {analysis.findings.map((f, i) => (
                  <FindingRow key={i} finding={f} />
                ))}
              </div>
            ) : (
              <p className="text-sm text-slate-500">No specific findings to report.</p>
            )}
          </div>

          {/* Inconsistencies */}
          <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
            <h2 className="text-lg font-bold text-slate-900 mb-4">Story vs. Records</h2>
            {analysis.inconsistencies.length > 0 ? (
              <div className="space-y-3">
                {analysis.inconsistencies.map((inc, i) => (
                  <div key={i} className={`rounded-lg border p-3 ${
                    inc.severity === "critical"
                      ? "border-red-200 bg-red-50"
                      : "border-yellow-200 bg-yellow-50"
                  }`}>
                    <p className={`text-xs font-semibold uppercase tracking-wide mb-1 ${
                      inc.severity === "critical" ? "text-red-700" : "text-yellow-700"
                    }`}>
                      {inc.severity === "critical" ? "⚠ Inconsistency Detected" : "△ Possible Discrepancy"}
                    </p>
                    <p className="text-sm font-medium text-slate-800">{inc.field}</p>
                    <p className="text-xs text-slate-600 mt-1">
                      <span className="font-medium">Your story:</span> {inc.narrativeSays}
                    </p>
                    <p className="text-xs text-slate-600">
                      <span className="font-medium">Documents show:</span> {inc.documentSays}
                    </p>
                  </div>
                ))}
              </div>
            ) : (
              <div className="flex items-center gap-2 text-sm text-green-700">
                <CheckCircle2 className="h-4 w-4" />
                No inconsistencies detected between your story and documents.
              </div>
            )}

            {/* Missing documents */}
            {analysis.documentsMissing.length > 0 && (
              <div className="mt-4">
                <h3 className="text-sm font-semibold text-slate-700 mb-2">Possibly Missing Documents</h3>
                <div className="space-y-1">
                  {analysis.documentsMissing.map((doc, i) => (
                    <div key={i} className="flex items-center gap-2 text-sm text-slate-600">
                      <XCircle className="h-3.5 w-3.5 text-slate-400 shrink-0" />
                      {doc}
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Plain Language Summary */}
        <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <h2 className="text-lg font-bold text-slate-900 mb-4">What This Means</h2>
          <div className="prose prose-slate prose-sm max-w-none">
            {analysis.plainLanguageSummary.split("\n").map((para, i) => (
              para.trim() ? <p key={i} className="text-slate-700 leading-relaxed">{para}</p> : null
            ))}
          </div>
        </div>

        {/* Next Steps */}
        <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <h2 className="text-lg font-bold text-slate-900 mb-4">Possible Next Steps</h2>
          <p className="text-xs text-slate-500 mb-4 italic">
            These are possibilities for you to investigate — not legal recommendations. An immigration attorney can help determine which, if any, apply to your specific situation.
          </p>
          <div className="space-y-3">
            {analysis.nextSteps.map((step, i) => (
              <div key={i} className={`rounded-xl border p-4 ${
                step.recommended
                  ? "border-blue-200 bg-blue-50"
                  : "border-slate-200 bg-slate-50"
              }`}>
                <div className="flex items-center gap-2 mb-1">
                  <span className={`text-xs font-bold uppercase tracking-wide ${
                    step.recommended ? "text-blue-600" : "text-slate-500"
                  }`}>
                    {step.option}
                  </span>
                  {step.recommended && (
                    <span className="rounded-full bg-blue-100 text-blue-700 text-xs px-2 py-0.5 font-medium">
                      Suggested
                    </span>
                  )}
                </div>
                <p className="text-sm font-semibold text-slate-900">{step.title}</p>
                <p className="mt-1 text-sm text-slate-600">{step.description}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Immigration Timeline */}
        {analysis.timeline.length > 0 && (
          <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
            <h2 className="text-lg font-bold text-slate-900 mb-2">Immigration Timeline</h2>
            <div className="flex items-center gap-4 mb-5 text-xs text-slate-500">
              <span className="flex items-center gap-1.5"><span className="h-2.5 w-2.5 rounded-full bg-blue-500 inline-block" />From documents</span>
              <span className="flex items-center gap-1.5"><span className="h-2.5 w-2.5 rounded-full bg-green-500 inline-block" />Documents + narrative</span>
              <span className="flex items-center gap-1.5"><span className="h-2.5 w-2.5 rounded-full bg-slate-300 inline-block" />From narrative</span>
            </div>
            <div>
              {analysis.timeline.map((event, i) => (
                <TimelineRow key={i} event={event} />
              ))}
            </div>
          </div>
        )}

        {/* Disclaimer */}
        <Disclaimer text={analysis.disclaimer} />

        {/* Attorney CTA */}
        <div className="rounded-2xl border border-blue-200 bg-blue-50 p-6 text-center">
          <h2 className="text-lg font-bold text-blue-900">Ready to speak with an attorney?</h2>
          <p className="mt-2 text-sm text-blue-700">
            Export your complete case package — the attorney gets a structured summary,
            timeline, and issue list so they can focus on legal analysis from minute one.
          </p>
          <button
            onClick={() => exportCasePackage(analysis)}
            className="mt-4 inline-flex items-center gap-2 rounded-lg bg-blue-700 px-6 py-2.5 text-sm font-medium text-white hover:bg-blue-800 transition-colors"
          >
            <Download className="h-4 w-4" />
            Download Attorney Case Package
          </button>
        </div>
      </main>

      <footer className="mt-12 border-t border-slate-200 bg-white py-6 text-center text-xs text-slate-500">
        © {new Date().getFullYear()} MyImmigration — Case Intelligence Platform. Not a law firm. Not legal advice.
      </footer>
    </div>
  );
}
